apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    categories: Monitoring,Developer Tools
    containerImage: quay.io/kruize/kruize-operator:0.0.2
    description: Kruize provides resource optimization recommendations for Kubernetes
      workloads
    repository: https://github.com/kruize/kruize-operator
  name: kruize-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Kruize is the Schema for the kruizes API
      displayName: Kruize
      kind: Kruize
      name: kruizes.my.domain
      version: v1alpha1
  description: |
    Kruize is an resource optimization tool for Kubernetes workloads. It analyzes application performance metrics and provides right-sizing recommendations to optimize resource utilization, reduce costs, and improve application performance.
    ## Prerequisites
    - Prometheus for metrics collection. If not already installed in your cluster, please install using your preferred method.
  displayName: Kruize Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - monitoring
  - resource optimization
  - right-sizing recommendations
  - performance
  - cost
  links:
  - name: Kruize Operator
    url: https://github.com/kruize/kruize-operator
  - name: Kruize
    url: https://github.com/kruize/autotune
  maintainers:
  - email: dgunigun@ibm.com
    name: Dinakar Guniguntala
  - email: csubrama@ibm.com
    name: Chandrakala Subramanyam
  maturity: alpha
  minKubeVersion: 1.23.0
  provider:
    name: Kruize
  version: 0.0.0
